use Simpsonsdb;

INSERT INTO Characters (id, name, voice_actor, episode, air_date, image)
 VALUES (1,	"Akira",	"George Takei & Hank Azaria",	"One Fish Two Fish Blowfish Blue Fish",	'1991-01-24', "../assets/img/akira.jpg"),
(2,	"Ms. Albright",	"Tress MacNeille",	"The Telltale Head",	'1990-02-25', "../assets/img/msAlbright.jpg"),
(3,	"Aristotle Amadopolis",	"Jon Lovitz & Dan Castellaneta",	"Homer Defined",	'1991-10-17', "../assets/img/aristotleAmadopolis.jpg"),
(4,	"Atkins-State Comptroller",	"Harry Shearer & Hank Azaria",	"Lisa Gets an 'A'",	'1998-11-22', "../assets/img/atkinsStateComptroller.jpg"),
(5,	"Mary Bailey",	"Maggie Roswell",	"Two Cars in Every Garage and Three Eyes on Every Fish",	'1990-11-01', "../assets/img/maryBailey.jpg"),
(6,	"Birchibald 'Birch' T. Barlow",	"Harry Shearer",	"Sideshow Bob Roberts",	'1994-10-09', "../assets/img/birchibaldBarlow.jpg"),
(7,	"Bart Simpson",	"Nancy Cartwright",	"Good Night (The Simpsons short)",	'1987-04-19', "../assets/img/bartSimpson.jpg"),
(8,	"Jasper Beardly",	"Harry Shearer",	"Bart the General",	'1990-01-21', "../assets/img/jasperBeardly.jpg"),
(9,	"Benjamin Doug and Gary",	"Harry Shearer & Hank Azaria & Dan Castellaneta",	"Homer Goes to College",	'1993-10-14', "../assets/img/BenjaminDougGary.jpg"),
(10, "Bill and Marty",	"Dan Castellaneta & Harry Shearer",	"Bart vs. Thanksgiving",	'1990-10-11', "../assets/img/BillMarty.jpg"),
(11,	"Blinky",	"Unvoiced",	"Two Cars in Every Garage and Three Eyes on Every Fish",	'1990-11-01', "../assets/img/blinky.jpg"),
(12,	"Blue Haired Lawyer",	"Dan Castellaneta",	"Bart Gets Hit by a Car",	'1991-01-10', "../assets/img/blueHairedLawyer.jpg"),
(13,	"Boobarella",	"Tress MacNeille",	"I'm Spelling as Fast as I Can",	'2003-02-16', "../assets/img/boobarella.jpg"),
(14,	"Wendell Borton",	"Russi Taylor",	"Homer's Odyssey",	'1990-01-21', "../assets/img/wendellBorton.jpg"),
(15,	"Jacqueline Bouvier",	"Julie Kavner",	"Bart vs. Thanksgiving",	'1990-02-11', "../assets/img/Jacqueline_Bouvier.png"),
(16,	"Patty Bouvier",	"Julie Kavner",	"Simpsons Roasting on an Open Fire",	'1989-12-17', "../assets/img/patty_bouvier.png"),
(17,	"Selma Bouvier",	"Julie Kavner",	"Simpsons Roasting on an Open Fire",	'1989-12-17', "../assets/img/selma_bouvier.png"),
(18,	"Kent Brockman",	"Harry Shearer",	"Krusty Gets Busted",	'1990-04-29', "../assets/img/Kent_Brockman.png"),
(19,	"Bumblebee Man",	"Hank Azaria",	"Itchy & Scratchy: The Movie",	'1992-11-03', "../assets/img/Bumblebee_man.png"),
(20,	"Charles Montgomery Burns",	"Christopher Collins (early season 1) & Harry Shearer",	"Simpsons Roasting on an Open Fire",	'1989-12-17', "../assets/img/Montgomery_Burns.png"),
(21,	"Capital City Goofball",	"Tom Poston",	"Dancin' Homer",	'1990-11-08', "../assets/img/Capital_City_Goofball.png"),
(22,	"Carl Carlson",	"Hank Azaria",	"Homer's Night Out",	'1990-03-25', "../assets/img/carl_carlson.png"),
(23,	"Gary Chalmers",	"Hank Azaria",	"Whacking Day",	'1993-04-29', "../assets/img/garyChalmers.jpg"),
(24,	"Charlie",	"Dan Castellaneta",	"Life on the Fast Lane",	'1990-03-18', "../assets/img/"),
(25,	"Chase (Pyro)",	"Hank Azaria",	"A Milhouse Divided",	'1996-12-01', "../assets/img/Chase_pyro.png"),
(26,	"Scott Christian",	"Dan Castellaneta",	"Krusty Gets Busted",	'1990-04-29', "../assets/img/Scott_Christian.png"),
(27,	"Coach Lugash",	"Dan Castellaneta",	"Children of a Lesser Clod",	'2001-05-13', "../assets/img/coachLugash"),
(28,	"Comic Book Guy",	"Hank Azaria",	"Three Men and a Comic Book",	'1991-05-09',"../assets/img/Comic_Book_Guy.png"),
(29,	"Mr. Costington",	"Hank Azaria",	"Trash of the Titans",	'1998-04-26',"../assets/img/Mr._Costington"),
(30,	"Crazy Cat Lady",	"Tress MacNeille",	"Girly Edition",	'1998-04-19',"../assets/img/crazyCatLady"),
(31,	"Database",	"Nancy Cartwright",	"Bart's Comet",	'1995-02-05',"../assets/img/database.jpg"),
(32,	"Declan Desmond",	"Eric Idle",	"'Scuse Me While I Miss the Sky",	'2003-03-20',"../assets/img/Declan_desmond.png"),
(33,	"Disco Stu",	"Hank Azaria",	"Two Bad Neighbors",	'1996-01-14',"../assets/img/Disco_Stu.png"),
(34,	"Dolph",	"Tress MacNeille",	"The Telltale Head",	'1990-02-25',"../assets/img/Dolph_Starbeam.png"),
(35,	"Lunchlady Doris",	"Doris Grau (1991-1995) & Tress MacNeille (1996-present)",	"Lisa's Pony",	'1991-11-07',"../assets/img/lunchLadyDoris"),
(36,	"Dr. Nick Riviera",	"Hank Azaria",	"Bart Gets Hit by a Car",	'1991-01-10',"../assets/img/Nick_Riviera.png"),
(37,	"Duffman",	"Hank Azaria",	"The City of New York vs. Homer Simpson",	'1997-09-21',"../assets/img/Duff_man.png"),
(38,	"Eddie and Lou",	"Harry Shearer & Hank Azaria",	"There's No Disgrace Like Home",	'1990-01-28',"../assets/img/eddie_and_lou.png"),
(39,	"Fat Tony",	"Joe Mantegna",	"Bart the Murderer",	'1991-10-10', "../assets/img/Fat_Tony.jpg"),
(40,	"Maude Flanders",	"Maggie Roswell",	"Dead Putting Society",	'1990-11-15', "../assets/img/maude_flanders.png"),
(41,	"Ned Flanders",	"Harry Shearer",	"Simpsons Roasting on an Open Fire",	'1989-12-17', "../assets/img/Ned_Flanders.png"),
(42,	"Rod Flanders",	"Pamela Hayden",	"The Call of the Simpsons",	'1990-02-18', "../assets/img/Rod_flanders.jpg"),
(43,	"Todd Flanders",	"Nancy Cartwright",	"Simpsons Roasting on an Open Fire",	'1989-12-17', "../assets/img/Todd_Flanders.png"),
(44,	"Francesca",	"Maria Grazia Cucinotta",	"The Italian Bob",	'2005-12-11', "../assets/img/francesca.jpg"),
(45,	"Frankie the Squealer",	"Dan Castellaneta",	"Insane Clown Poppy",	'2000-11-12', "../assets/img/Frankie_the_Squealer.png"),
(46,	"Professor John Frink",	"Hank Azaria",	"Old Money",	'1991-03-28', "../assets/img/Professor_Frink.png"),
(47,	"Baby Gerald",	"Unvoiced",	"Sweet Seymour Skinner's Baadasssss Song",	'1994-04-28', "../assets/img/Baby_Gerald.png"),
(48,	"Ginger Flanders",	"Tress MacNeille",	"Viva Ned Flanders",	'1999-01-10', "../assets/img/Ginger_Flanders.png"),
(49,	"Gino Terwilliger",	"Tress MacNeille",	"The Italian Bob",	'2005-12-11', "../assets/img/Gino_terwilliger.png"),
(50,	"Alice Glick",	"Cloris Leachman & Tress MacNeille",	"Three Men and a Comic Book",	'1991-05-09', "../assets/img/Alice_Glick.png"),
(51,	"Gloria Jailbird",	"Julia Louis-Dreyfus",	"A Hunka Hunka Burns in Love",	'2001-12-02', "../assets/img/Gloria_jailbird.png"),
(52,	"Groundskeeper Willie",	"Dan Castellaneta",	"Principal Charming",	'1991-02-14', "../assets/img/Groundskeeper_Willie.png"),
(53,	"Barney Gumble",	"Dan Castellaneta",	"Simpsons Roasting on an Open Fire",	'1989-12-17', "../assets/img/Barney_Gumble.png"),
(54,	"Gil Gunderson",	"Dan Castellaneta",	"Realty Bites",	'1997-12-07', "../assets/img/Gil_Gunderson.png"),
(55,	"Judge Constance Harm",	"Jane Kaczmarek",	"The Parent Rap",	'2001-11-11', "../assets/img/judge.png"),
(56,	"Herman Hermann",	"Harry Shearer",	"Bart the General",	'1990-02-04', "../assets/img/Herman_Hermann.png"),
(57,	"Bernice Hibbert",	"Tress MacNeille",	"Bart's Dog Gets an 'F'",	'1991-03-07', "../assets/img/Bernice_Hibbert.png"),
(58,	"Dr. Julius Hibbert",	"Harry Shearer",	"Bart the Daredevil",	'1990-12-06', "../assets/img/drJulius_hibbert.png"),
(59,	"Homer Simpson",	"Dan Castellaneta",	"Good Night (The Simpsons short)",	'1987-04-19', "../assets/img/Homer_Simpson.png"),
(60,	"Elizabeth Hoover",	"Maggie Roswell",	"Brush with Greatness",	'1991-04-11', "../assets/img/Elizabeth_Hoover.png"),
(61,	"Lionel Hutz",	"Phil Hartman",	"Bart Gets Hit by a Car",	'1991-01-10', "../assets/img/Lionel_Hutz.png"),
(62,	"Itchy & Scratchy",	"Dan Castellaneta & Harry Shearer",	"There's No Disgrace Like Home",	'1988-11-20', "../assets/img/Itchy_and_Scratchy.gif"),
(63,	"Jacques",	"Albert Brooks",	"Life on the Fast Lane",	'1990-03-18', "../assets/img/Jacques.png"),
(64,	"Jake",	"Dan Castellaneta & Harry Shearer",	"Simpson and Delilah",	'1987-11-15', "../assets/img/JakeTheBarber.png"),
(65,	"Jimbo Jones",	"Pamela Hayden",	"The Telltale Head",	'1990-02-25', "../assets/img/Jimbo.png"),
(66,	"Rachel Jordan",	"Shawn Colvin",	"Alone Again Natura-Diddily",	'2000-02-13', "../assets/img/Rachel_Jordan.png"),
(67,	"Kang and Kodos",	"Harry Shearer & Dan Castellaneta",	"Treehouse of Horror",	'1990-10-25', "../assets/img/Kang_and_Kodos.png"),
(68,	"Princess Kashmir",	"Maggie Roswell",	"Homer's Night Out",	'1990-03-25', "../assets/img/princesskashmir.png"),
(69,	"Edna Krabappel",	"Marcia Wallace",	"Bart the Genius",	'1990-01-14', "../assets/img/Edna_Krabappel.png"),
(70,	"Rabbi Hyman Krustofski",	"Jackie Mason & Dan Castellaneta",	"Like Father Like Clown",	'1991-10-24', "../assets/img/rabbi_hyman.png"),
(71,	"Krusty the Clown",	"Dan Castellaneta",	"The Telltale Head",	'1989-01-15', "../assets/img/krusty_the_clown.png"),
(72,	"Cookie Kwan",	"Tress MacNeille",	"Realty Bites",	'1997-12-07', "../assets/img/Cookie_Kwan.png"),
(73,	"Dewey Largo",	"Harry Shearer",	"Simpsons Roasting on an Open Fire",	'1989-12-17', "../assets/img/Dewey_Largo.png"),
(74,	"Legs and Louie",	"Hank Azaria & Dan Castellaneta",	"Bart the Murderer",	'1991-10-10', "../assets/img/LegsandLouie.jpg"),
(75,	"Lenny Leonard",	"Harry Shearer",	"Life on the Fast Lane",	'1990-03-18', "../assets/img/lenny_leonard.png"),
(76,	"Leopold",	"Dan Castellaneta",	"Sweet Seymour Skinner's Baadasssss Song",	'1994-04-28', "../assets/img/Leopold.png"),
(77,	"Lewis Clark",	"Russi Taylor",	"Simpsons Roasting on an Open Fire",	'1989-12-17', "../assets/img/lewis_clark.PNG"),
(78,	"Lisa Simpson",	"Yeardley Smith",	"Good Night (The Simpsons short)",	'1987-04-19', "../assets/img/Lisa.png"),
(79,	"Helen Lovejoy",	"Maggie Roswell",	"Life on the Fast Lane",	'1990-03-18', "../assets/img/helenLovejoy.jpg"),
(80,	"Reverend Timothy Lovejoy",	"Harry Shearer",	"The Telltale Head",	'1990-02-25', "../assets/img/reverend_timothy.png"),
(81,	"Lurleen Lumpkin",	"Beverly D'Angelo\Doris Grau",	"Colonel Homer",	'1992-03-26', "../assets/img/Lurleen_Lumpkin.png"),
(82,	"Maggie Simpson",	"Liz Georges & Gábor Csupó & Harry Shearer & Yeardley Smith & Nancy Cartwright & Elizabeth Taylor & James Earl Jones & Jodie Foster",	"Good Night (The Simpsons short)",	'1987-04-19', "../assets/img/Maggie-Simpson.png"),
(83,	"Otto Mann",	"Harry Shearer",	"Homer's Odyssey",	'1990-01-21', "../assets/img/Otto_mann.png"),
(84,	"Marge Simpson",	"Julie Kavner",	"Good Night (The Simpsons short)",	'1987-04-19', "../assets/img/Marge_Simpson.png"),
(85,	"Captain Horatio McCallister",	"Hank Azaria",	"New Kid on the Block",	'1992-11-12', "../assets/img/Horatio_McCallister.png"),
(86,	"Troy McClure",	"Phil Hartman",	"Homer vs. Lisa and the 8th Commandment",	'1991-02-07', "../assets/img/Troy_McClure.jpg"),
(87,	"Roger Meyers Jr.",	"Alex Rocco & Dan Castellaneta",	"Itchy & Scratchy & Marge",	'1990-12-20', "../assets/img/Roger_Meyers,_Jr..png"),
(88,	"Hans Moleman",	"Dan Castellaneta",	"Principal Charming",	'1991-02-14', "../assets/img/Hans_Moleman.png"),
(89,	"Dr. Marvin Monroe",	"Harry Shearer",	"There's No Disgrace Like Home",	'1990-01-28', "../assets/img/Marvin_Monroe.png"),
(90,	"Captain Lance Murdock",	"Dan Castellaneta",	"Bart the Daredevil",	'1990-12-06', "../assets/img/Lance_Murdock.png"),
(91,	"Bleeding Gums Murphy",	"Ron Taylor",	"Moaning Lisa",	'1990-02-11', "../assets/img/Bleeding_Gums_Murphy.png"),
(92,	"Lindsey Naegle",	"Tress MacNeille",	"The Itchy & Scratchy & Poochie Show",	'1997-02-09', "../assets/img/Lindsey_Naegle.png"),
(93,	"Apu Nahasapeemapetilon",	"Hank Azaria",	"The Telltale Head",	'1990-02-25', "../assets/img/Apu_Naha.png"),
(94,	"Manjula Nahasapeemapetilon",	"Jan Hooks(1997-2002) & Tress MacNeille (2014-present)",	"Much Apu About Nothing",	'1997-11-16', "../assets/img/ManjulaNaha.jpg"),
(95,	"Sanjay Nahasapeemapetilon",	"Harry Shearer",	"Dog of Death",	'1997-11-16', "../assets/img/Sanjay_Naha.png"),
(96,	"Nelson Muntz",	"Nancy Cartwright",	"Bart the General",	'1990-02-04', "../assets/img/Nelson_Muntz.png"),
(97,	"Old Jewish Man",	"Hank Azaria",	"Krusty Gets Kancelled",	'1993-05-13', "../assets/img/oldJewishMan.jpg"),
(98,	"Patches and Poor Violet",	"Pamela Hayden & Tress MacNeille",	"Miracle on Evergreen Terrace",	'1997-12-21', "../assets/img/Patches_and_poor_Violet.png"),
(99,	"Herbert Powell",	"Danny DeVito",	"Oh Brother Where Art Thou?",	'1991-02-21', "../assets/img/HerbPowell.png"),
(100,	"Janey Powell",	"Pamela Hayden",	"Moaning Lisa",	'1990-02-04', "../assets/img/Janey_powell.png"),
(101,	"Ruth Powers",	"Pamela Reed",	"New Kid on the Block",	'1992-11-12', "../assets/img/Ruth_Powers.png"),
(102,	"Martin Prince",	"Russi Taylor",	"Bart the Genius",	'1990-01-14', "../assets/img/Martin_Prince.png"),
(103,	"Loren Pryor",	"Harry Shearer",	"Bart the Genius",	'1990-01-14', "../assets/img/Loren_Pyror.png"),
(104,	"Arnie Pye",	"Dan Castellaneta",	"Homer Alone",	'1992-02-06', "../assets/img/Arnie_Pye.png"),
(105,	"Mayor 'Diamond' Joe Quimby",	"Dan Castellaneta",	"The Call of the Simpsons",	'1990-10-11', "../assets/img/Mayor_Quimby.png"),
(106,	"Radioactive Man",	"Harry Shearer",	"Three Men and a Comic Book",	'1990-01-14', "../assets/img/radioactive.png"),
(107,	"Raphael",	"Hank Azaria",	"The Way We Was",	'1991-01-31', "../assets/img/Rafael.png"),
(108,	"The Rich Texan",	"Dan Castellaneta",	"$pringfield (Or How I Learned to Stop Worrying and Love Legalized Gambling)",	'1993-12-16', "../assets/img/The_Rich_texan.png"),
(109,	"Richard",	"Pamela Hayden & Nancy Cartwright",	"Bart the Genius",	'1990-01-14', "../assets/img/The_Simpsons_Richard.png"),
(110,	"Luigi Risotto",	"Hank Azaria",	"Sweet Seymour Skinner's Baadasssss Song",	'1994-04-28', "../assets/img/luigi.jpg"),
(111,	"Robert Terwilliger",	"Kelsey Grammer",	"The Telltale Head",	'1990-02-25', "../assets/img/Robert_Terwilliger.png"),
(112,	"Santa's Little Helper",	"Dan Castellaneta & Frank Welker",	"Simpsons Roasting on an Open Fire",	'1989-12-17', "../assets/img/Santa's_Little_Helper.png"),
(113,	"Sherri and Terri",	"Russi Taylor",	"Homer's Odyssey",	'1990-01-21', "../assets/img/Sherri_Terri.png"),
(114,	"Dave Shutton",	"Harry Shearer",	"Two Cars in Every Garage and Three Eyes on Every Fish",	'1990-11-01', "../assets/img/Dave_Shutton.png"),
(115,	"Sideshow Mel",	"Dan Castellaneta",	"Itchy & Scratchy & Marge",	'1990-12-20', "../assets/img/Sideshow_Mel.png"),
(116,	"Amber Simpson",	"Pamela Hayden",	"Viva Ned Flanders",	'1999-01-10', "../assets/img/amberSimpson.jpg"),
(117,	"Grampa Simpson",	"Dan Castellaneta",	"Grampa and the Kids(The Simpsons shorts)",	'1988-01-10', "../assets/img/Grampa.png"),
(118,	"Mona Simpson",	"Glenn Close & Tress MacNeille & Maggie Roswell",	"Oh Brother Where Art Thou?",	'1991-02-21', "../assets/img/mona_simpson.png"),
(119,	"Agnes Skinner",	"Tress MacNeille",	"The Crepes of Wrath",	'1990-04-15', "../assets/img/Agnes_Skinner.png"),
(120,	"Seymour Skinner",	"Harry Shearer",	"Simpsons Roasting on an Open Fire",	'1989-12-17', "../assets/img/Seymour_Skinner.png"),
(121,	"Waylon Smithers",	"Harry Shearer",	"Simpsons Roasting on an Open Fire",	'1990-01-21', "../assets/img/Waylon_Smithers.png"),
(122,	"Snake Jailbird",	"Hank Azaria",	"The War of the Simpsons",	'1991-05-02', "../assets/img/snake_jailbird.png"),
(123,	"Snowball II",	"Frank Welker",	"Simpsons Roasting on an Open Fire",	'1989-12-17', "../assets/img/snowball2.png"),
(124,	"Roy Snyder",	"Harry Shearer",	"Krusty Gets Busted",	'1990-04-29', "../assets/img/Roy_Snyder.png"),
(125,	"Jebediah Springfield",	"Harry Shearer",	"The Telltale Head",	'1990-02-25', "../assets/img/JebediahSpringfield.png"),
(126,	"Brandine Spuckler",	"Tress MacNeille",	"Scenes from the Class Struggle in Springfield",	'1996-02-04', "../assets/img/brandine_spuckler.png"),
(127,	"Cletus Spuckler",	"Hank Azaria",	"Bart Gets an Elephant",	'1994-03-31', "../assets/img/Cletus_Spuckler"),
(128,	"Squeaky-Voiced Teen",	"Dan Castellaneta",	"Dog of Death",	'1991-02-14', "../assets/img/squeakyVoiceTeen.jpg"),
(129,	"Moe Szyslak",	"Hank Azaria",	"Simpsons Roasting on an Open Fire",	'1989-12-17', "../assets/img/Moe_Szyslak.png"),
(130,	"Drederick Tatum",	"Hank Azaria",	"Homer vs Lisa and the 8th Commandment",	'1991-02-07', "../assets/img/Drederick_tatum.png"),
(131,	"Allison Taylor",	"Winona Ryder & Pamela Hayden",	"Lisa's Rival",	'1994-09-11', "../assets/img/Allison_taylor.png"),
(132,	"Mr. Teeny",	"Dan Castellaneta",	"Like Father Like Clown",	'1991-10-24', "../assets/img/Mr_Teeny.png"),
(133,	"Cecil Terwilliger",	"David Hyde Pierce",	"Brother from Another Series",	'1997-02-23', "../assets/img/cecil_terw.png"),
(134,	"The Happy Little Elves",	"Dan Castellaneta & Hank Azaria & Harry Shearer",	"Simpsons Roasting on an Open Fire",	'1989-02-12', "../assets/img/Happy_Little_Elves.png"),
(135,	"Johnny Tightlips",	"Hank Azaria",	"Insane Clown Poppy",	'2000-11-12', "../assets/img/Johnny_Tightlips.png"),
(136,	"Kirk Van Houten",	"Hank Azaria",	"Bart's Friend Falls in Love",	'1992-05-07', "../assets/img/Kirk_Van_Houten.png"),
(137,	"Luann Van Houten",	"Maggie Roswell",	"Homer Defined",	'1991-10-17', "../assets/img/Luann_Van_Houten.png"),
(138,	"Milhouse Van Houten",	"Pamela Hayden",	"Simpsons Roasting on an Open Fire",	'1989-12-17', "../assets/img/milhouse.jpg"),
(139,	"Dr. Velimirovic",	"Hank Azaria",	"Pygmoelian",	'2000-02-27', "../assets/img/Dr._velimirovic.png"),
(140,	"Police Chief Clancy Wiggum",	"Hank Azaria",	"Homer's Odyssey",	'1990-01-21', "../assets/img/police_chief_wiggum.png"),
(141,	"Ralph Wiggum",	"Nancy Cartwright",	"Simpsons Roasting on an Open Fire",	'1991-02-07', "../assets/img/Ralph_Wiggum.png"),
(142,	"Sarah Wiggum",	"Pamela Hayden",	"Duffless",	'1993-02-18', "../assets/img/Sarah_Wiggum.png"),
(143,	"Rainier Wolfcastle (McBain)",	"Harry Shearer",	"The Way We Was",	'1991-01-31', "../assets/img/McBain.png"),
(144,	"The Yes Guy",	"Dan Castellaneta",	"Mayored to the Mob",	'1998-12-20', "../assets/img/Yes_Guy.png"),
(145,	"Artie Ziff",	"Jon Lovitz & Dan Castellaneta",	"The Way We Was",	'1991-01-31', "../assets/img/Artie_Ziff.png"),
(146,	"Kearney Zzyzwicz",	"Nancy Cartwright",	"The Telltale Head",	'1990-02-25', "../assets/img/Kearney_Zzyzwicz.png"),
(147,	"Üter Zörker",	"Russi Taylor",	"Treehouse of Horror IV",	'1993-10-28', "../assets/img/uterZorker.jpg");